### ISSUE TITLE
Separate icon for saved comment

### ISSUE THREAD

**Issue by matrixik** [OctoNezd/oldlander#80]
**Describe the bug**
Now the icon for saving looks the same regardless if post is saved or not.

**To Reproduce**
1. Go to https://old.reddit.com/r/VOIP/comments/1134uvd/headset_with_solid_noise_rejection_for_a_call/j9343ss/
2. Click on save icon

**Expected behavior**
Easily distinguishable icons for saved content.

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - OS: Android 13 
 - Browser: Firefox 121.0
 - Add-on Version: 1.1.0.208

**Reddit page where bug can be easily reproduced**
https://old.reddit.com/r/VOIP/comments/1134uvd/headset_with_solid_noise_rejection_for_a_call/j9343ss/

**Additional context**
I'm mostly using phone in greyscale mode so I would prefer if this icons differ in shape instead of differing in color.
Would be nice if icons could be bigger on mobile.

Thank you for working on this great add-on.

**Comment by matrixik** [comment]
Hmm, I think it's working when saving main story but not when saving comments.

**Comment by OctoNezd** [comment]
Should be fixed in latest release.

**Comment by OctoNezd** [comment]
![image](https://github.com/OctoNezd/oldlander/assets/15308404/edccf2e5-f4c4-4dae-8442-9038c370ffa3)

Well, once mozilla removes cooldown :)

**Comment by OctoNezd** [comment]
> Would be nice if icons could be bigger on mobile

Button design changed on latest commit
![image](https://github.com/OctoNezd/oldlander/assets/15308404/49c403a8-39df-47a8-8f03-6907180771f6)

**Comment by matrixik** [comment]
Thank you for working on this. Unfortunately looks like with last version now save icon does not change even for saving posts (previously was changing to trash bin).
Did you tried checking saved post/comment? On old reddit style it's showing 'unsave' text but when I turn on your add-on and refresh page it's still showing save icon.

When you visit link I provided you could also see some missing styles:
![Screenshot_20240101-205142](https://github.com/OctoNezd/oldlander/assets/201930/7a12673e-9fdb-4892-b8b8-8a5a80198af1)

**Comment by matrixik** [comment]
And thank you for making icons bigger, it's really useful on mobile.
I think they are somewhat too light compared to rest of the dark style but it's okay.

**Comment by OctoNezd** [comment]
Huh. Thats weird. I will look into this issue

**Comment by matrixik** [comment]
> And thank you for making icons bigger, it's really useful on mobile. I think they are somewhat too light compared to rest of the dark style but it's okay.

Oh, I see now what you did, you used colors from Material theme for icons https://m2.material.io/design/color/dark-theme.html
But rest of the page is not using colors from Material so links like username or subreddits on main page have too low contrast and are hard to read 
https://coolors.co/contrast-checker/336699-000000

**Comment by matrixik** [comment]
Thank you for fixing this problem and updating colors.
